// <auto-generated />
using System;
using FaSoLaSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaSoLaSearch.Migrations
{
    [DbContext(typeof(PartContext))]
    [Migration("20251107021053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaSoLaSearch.Models.Song", b =>
                {
                    b.Property<Guid>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("Eighth")
                        .HasColumnType("character(1)");

                    b.Property<char>("Fifth")
                        .HasColumnType("character(1)");

                    b.Property<char>("First")
                        .HasColumnType("character(1)");

                    b.Property<char>("Fourth")
                        .HasColumnType("character(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Part")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Second")
                        .HasColumnType("character(1)");

                    b.Property<char>("Seventh")
                        .HasColumnType("character(1)");

                    b.Property<char>("Sixth")
                        .HasColumnType("character(1)");

                    b.Property<char>("Third")
                        .HasColumnType("character(1)");

                    b.HasKey("SongId");

                    b.ToTable("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
